name: build
permissions:
  contents: read

on:
  push:
    branches: [main, dev]
    paths-ignore:
      - 'Docs/**'       # Docs folder in root of repo
      - '**/*.md'       # .md files anywhere in the repo
      - '**/LICENSE'    # LICENSE files anywhere in the repo
      - '**/.gitignore' # .gitignore files anywhere in the repo
      
  pull_request:
    branches: [main]
    paths-ignore:
      - 'Docs/**'       # Docs folder in root of repo
      - '**/*.md'       # .md files anywhere in the repo
      - '**/LICENSE'    # LICENSE files anywhere in the repo
      - '**/.gitignore' # .gitignore files anywhere in the repo
      
  workflow_dispatch:
    
  schedule:
  - cron: '40 12 * * *'   # once a day @ 12:40pm UTC (5:40am PST)

env:
  SCHEME: swift-testing-extensions
  WORKSPACEPATH: .swiftpm/xcode/package.xcworkspace

jobs:
  macOS:
    name: Tests (macOS)
    runs-on: macos-latest
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@main
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - name: Build
      run: |
        PARAMS=(
          -skipMacroValidation
          -workspace "$WORKSPACEPATH"
          -scheme "$SCHEME"
          -destination "generic/platform=macOS"
        )
        xcodebuild build "${PARAMS[@]}" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
    - name: Unit Tests
      run: |
        PARAMS=(
          -skipMacroValidation
          -workspace "$WORKSPACEPATH"
          -scheme "$SCHEME"
          -destination "platform=macOS"
        )
        xcodebuild test "${PARAMS[@]}" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
  
  macCatalyst:
    name: Tests (macCatalyst)
    runs-on: macos-15
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@main
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - name: Build
      run: |
        # As a workaround for flakey pre-builds included in SwiftSyntax, we have to disable them when testing any platform that isn't macOS
        # See: https://github.com/swiftlang/swift-syntax/issues/2421#issuecomment-3542406416
        PARAMS=(
          -skipMacroValidation
          -workspace "$WORKSPACEPATH"
          -scheme "$SCHEME"
          -destination "generic/platform=macOS,variant=Mac Catalyst"
          -IDEPackageEnablePrebuilts=NO
        )
        xcodebuild build "${PARAMS[@]}" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
    - name: Delete Derived Data
      run: rm -rf ~/Library/Developer/Xcode/DerivedData
    - name: Unit Tests
      run: |
        # As a workaround for flakey pre-builds included in SwiftSyntax, we have to disable them when testing any platform that isn't macOS
        # See: https://github.com/swiftlang/swift-syntax/issues/2421#issuecomment-3542406416
        PARAMS=(
          -skipMacroValidation
          -workspace "$WORKSPACEPATH"
          -scheme "$SCHEME"
          -destination "platform=macOS,variant=Mac Catalyst"
          -IDEPackageEnablePrebuilts=NO
        )
        xcodebuild test "${PARAMS[@]}" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
  
  device-simulators:
    name: Tests
    runs-on: macos-latest
    strategy:
      matrix:
        target: [iOS, tvOS, watchOS, visionOS]
    continue-on-error: true
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@main
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - name: Prepare Device Simulator
      id: sim-setup
      uses: orchetect/setup-xcode-simulator@v1
      with:
        refresh: true
        download: true
        scheme: ${{ env.SCHEME }}
        target: ${{ matrix.target }}
    - name: Build
      run: |
        # As a workaround for flakey pre-builds included in SwiftSyntax, we have to disable them when testing any platform that isn't macOS
        # See: https://github.com/swiftlang/swift-syntax/issues/2421#issuecomment-3542406416
        PARAMS=(
          -skipMacroValidation
          -workspace "$WORKSPACEPATH"
          -scheme "$SCHEME"
          -destination "generic/platform=$PLATFORMSHORT"
          -IDEPackageEnablePrebuilts=NO
        )
        xcodebuild build "${PARAMS[@]}" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
      env:
        PLATFORMSHORT: ${{ steps.sim-setup.outputs.platform-short }}
        WORKSPACEPATH: ${{ steps.sim-setup.outputs.workspace-path }}
    - name: Delete Derived Data
      run: rm -rf ~/Library/Developer/Xcode/DerivedData
    - name: Unit Tests
      run: |
        # As a workaround for flakey pre-builds included in SwiftSyntax, we have to disable them when testing any platform that isn't macOS
        # See: https://github.com/swiftlang/swift-syntax/issues/2421#issuecomment-3542406416
        PARAMS=(
          -skipMacroValidation
          -workspace "$WORKSPACEPATH"
          -scheme "$SCHEME"
          -destination "platform=$PLATFORM,id=$ID"
          -IDEPackageEnablePrebuilts=NO
        )
        xcodebuild test "${PARAMS[@]}" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
      env:
        ID: ${{ steps.sim-setup.outputs.id }}
        PLATFORM: ${{ steps.sim-setup.outputs.platform }}
        WORKSPACEPATH: ${{ steps.sim-setup.outputs.workspace-path }}
